---
- name: install software packages using loops
  hosts: all
  become: yes
  tasks:
    - name: install softwares
      apt:
        name: "{{item}}"
        state: present
        update_cache: no
      with_items:
        - tree
        - git
        - default-jdk
        - apache2
